### ISSUE TITLE
Combat Tracker

### ISSUE THREAD

**Issue by WardLT** [WardLT/play-by-post-helper#12]
Build a stripped-down version of [Improved Initiative](https://www.improved-initiative.com/):

- [ ] Keep track of characters/NPCs participating in a combat
- [ ] Automate attack procedure: make roll, check for hit, compute damage, apply damage to target HP
- [ ] Keep track of damage and conditions for participants
- [ ] Render a full view of participant health/AC to GM, masked view to players
